import {
  ClientRow,
  StaffRow,
  CategoryRow,
  ProductRow,
  PaymentRow,
  ReceiptRow,
  CashShift,
  SalaryRow,
  CategoryLabel,
  InvoiceRow,
  MenuProduct,
  MenuRecipe,
  RecipeIngredient,
  ProductCategory,
} from '../types/accounting';

export const CATEGORY_LABELS: CategoryLabel = {
  rent: "Оренда",
  utilities: "Комунальні",
  salary: "Зарплата",
  supplies: "Поставки",
  marketing: "Маркетинг",
  maintenance: "Обслуговування",
  other: "Інше",
};

export const CATEGORIES = Object.keys(CATEGORY_LABELS);

export const MOCK_CLIENT_ROWS: ClientRow[] = [
  {
    name: "Ксенія",
    phone: "+380 67 231 3453",
    noDiscount: 5020,
    cash: 2000,
    card: 2520,
    profit: 4210.37,
    receipts: 1,
    avgCheck: 5020,
    id: '1',
    email: 'ksenya@example.com',
    address: '123 Main St',
    status: 'active',
  },
  {
    name: "Макар",
    phone: "",
    noDiscount: 150,
    cash: 150,
    card: 0,
    profit: 149,
    receipts: 1,
    avgCheck: 150,
    id: '2',
    email: 'macar@example.com',
    address: '123 Main St',
    status: 'active',
  },
  {
    name: "Оксана",
    phone: "",
    noDiscount: 570,
    cash: 369,
    card: 201.2,
    profit: 57.58,
    receipts: 9,
    avgCheck: 63.38,
    id: '3',
    email: 'oksana@example.com',
    address: '123 Main St',
    status: 'active',
  },
];

export const MOCK_STAFF_ROWS: StaffRow[] = [
  {
    id: "1",  // Add unique ID
    position: "Бариста",  // Add position
    name: "Валерія",
    revenue: 18604,
    profit: 15419.92,
    receipts: 11,
    avgCheck: 169.45,
    avgTime: "23 хвилини 41 секунда",
    workedTime: "25 годин 35 хвилин",
    salary: 15000,
    phone: "",
    email: "",
    status: "active",
  },
  {
    id: "2",  // Add unique ID
    position: "Бариста",  // Add position
    name: "Оксана",
    revenue: 14771.5,
    profit: 12730.48,
    receipts: 46,
    avgCheck: 321.12,
    avgTime: "868 хвилин 34 секунди",
    workedTime: "124 години 28 хвилин",
    salary: 15000,
    phone: "",
    email: "",
    status: "active",
  },
];

export const MOCK_CATEGORY_ROWS: CategoryRow[] = [
  {
    name: "Розважальні послуги",
    count: 236,
    cost: 1394.05,
    revenue: 42452,
    tax: 0,
    profit: 41057.95,
    foodCostPercent: 3.28,
  },
  {
    name: "Кухня",
    count: 128,
    cost: 4520.4,
    revenue: 7933,
    tax: 0,
    profit: 3412.6,
    foodCostPercent: 56.98,
  },
];

export const MOCK_PRODUCT_ROWS: ProductRow[] = [
  {
    name: "Бронювання залу ДН 1 дитина/1 година",
    modifier: "",
    count: 90,
    grossRevenue: 9000,
    discount: 50,
    revenue: 8950,
    profit: 8950,
  },
  {
    name: "Цукерка Тофік",
    modifier: "",
    count: 49,
    grossRevenue: 49,
    discount: 0,
    revenue: 49,
    profit: 14.7,
  },
];

export const MOCK_PAYMENT_ROWS: PaymentRow[] = [
  {
    date: "10 грудня",
    receiptsCount: 11,
    cash: 1419,
    card: 832,
    total: 2251,
    id: '1',
    method: 'cash',
    amount: 2251,
    status: 'completed',
  },
  {
    date: "9 грудня",
    receiptsCount: 4,
    cash: 275,
    card: 70,
    total: 345,
    id: '2',
    method: 'cash',
    amount: 345,
    status: 'completed',
  },
];

export const MOCK_RECEIPT_ROWS: ReceiptRow[] = [
  {
    id: '6328',
    risk: "",
    waiter: "Оля",
    openedAt: "10 грудня, 17:52",
    closedAt: "10 грудня, 17:55",
    paid: 400,
    discount: 0,
    profit: 18,
    status: "Закритий",
  },
  {
    id: '6327',
    risk: "",
    waiter: "Оля",
    openedAt: "10 грудня, 17:51",
    closedAt: "10 грудня, 17:52",
    paid: 245,
    discount: 85,
    profit: 2.02,
    status: "Закритий",
  },
];

export const MOCK_CASH_SHIFTS: CashShift[] = [
  {
    id: '1',
    date: '2023-12-10T10:00:00',
    cashier: 'Іванова О.П.',
    cash: 1419.00,
    cashless: 832.00,
    difference: 0,
    status: 'closed',
    register: 'Каса 1',
    openedAt: '2023-12-10T10:00:00',
    closedAt: '2023-12-10T10:00:00',
    openingBalance: 1419.00,
    closingBalance: 832.00
  }
];

export const MOCK_SALARY_ROWS: SalaryRow[] = [
  {
    id: '1',
    employee: 'Іванова Олена Петрівна',
    position: 'Адміністратор',
    salary: 15000.00,
    bonus: 1500.00,
    fine: 0,
    toPay: 16500.00,
    status: 'pending'
  },
];

export const MOCK_PRODUCT_CATEGORIES: ProductCategory[] = [
  {
    id: '1',
    name: 'Розважальні послуги',
    parentCategory: undefined,
    description: 'Основна категорія розважальних послуг',
    status: 'active',
    createdAt: '2024-01-15T10:00:00',
  },
  {
    id: '2',
    name: 'Кухня',
    parentCategory: undefined,
    description: 'Харчові послуги та напої',
    status: 'active',
    createdAt: '2024-01-15T10:00:00',
  },
  {
    id: '3',
    name: 'Готовий вареш',
    parentCategory: '2',
    description: 'Готові страви',
    status: 'active',
    createdAt: '2024-01-15T10:00:00',
  },
  {
    id: '4',
    name: 'Напої',
    parentCategory: '2',
    description: 'Гарячі та холодні напої',
    status: 'active',
    createdAt: '2024-01-15T10:00:00',
  },
  {
    id: '5',
    name: 'Головний екран',
    parentCategory: undefined,
    description: 'Категорія для головного екрану',
    status: 'active',
    createdAt: '2024-01-15T10:00:00',
  },
];

export const MOCK_MENU_RECIPES: MenuRecipe[] = [
  {
    id: '1',
    code: 'РЦ1',
    name: 'Борщ Українськіс',
    category: 'Кухня',
    yield: 0.215,
    yieldUnit: 'г',
    costPerUnit: 56.14,
    sellingPrice: 100.00,
    markup: 78,
    ingredients: [
      {
        id: '1',
        name: 'Сорячки стопові',
        quantity: 2,
        unit: 'шт',
        costPerUnit: 0,
        totalCost: 0.28,
      },
      {
        id: '2',
        name: 'Коробка з рукаво 200*140*60',
        quantity: 1,
        unit: 'шт',
        costPerUnit: 0,
        totalCost: 6.58,
      },
      {
        id: '3',
        name: 'соус гарячий в асортименті',
        quantity: 1,
        unit: 'шт',
        costPerUnit: 0,
        totalCost: 0.19,
      },
      {
        id: '4',
        name: 'картопля без оцтів',
        quantity: 110,
        unit: 'г',
        costPerUnit: 100,
        totalCost: 16.19,
      },
      {
        id: '5',
        name: 'олія рафінована олива 9.5л',
        quantity: 20,
        unit: 'мл',
        costPerUnit: 5,
        totalCost: 1.49,
      },
      {
        id: '6',
        name: 'сіль шт',
        quantity: 1,
        unit: 'шт',
        costPerUnit: 0,
        totalCost: 0.13,
      },
      {
        id: '7',
        name: 'Деревина цвіткова',
        quantity: 1,
        unit: 'шт',
        costPerUnit: 0,
        totalCost: 0.18,
      },
      {
        id: '8',
        name: 'напиток філе',
        quantity: 120,
        unit: 'г',
        costPerUnit: 110,
        totalCost: 25.19,
      },
    ],
    notes: 'Перераховано з 17 липня, 10:55',
    lastModified: '2024-07-17T10:55:00',
    modifiedBy: 'Ivan',
    status: 'active',
  },
  {
    id: '2',
    code: 'РЦ2',
    name: 'Борщ Українськіс',
    category: 'Готовий вареш',
    yield: 0.265,
    yieldUnit: 'г',
    costPerUnit: 59.48,
    sellingPrice: 100.00,
    markup: 68,
    ingredients: [],
    notes: 'Перераховано з 5 листопада 2024, 07:06',
    lastModified: '2024-11-05T07:06:00',
    modifiedBy: 'Ivan',
    status: 'active',
  },
];

export const MOCK_MENU_PRODUCTS: MenuProduct[] = [
  {
    id: '1',
    code: 'РИГ',
    name: 'Playstation 1 геймпад (1 год',
    category: 'Розважальні послуги',
    costPerUnit: 1.00,
    sellingPrice: 100.00,
    markup: 9900,
    status: 'active',
  },
  {
    id: '2',
    code: 'РИГ',
    name: 'Playstation 1 геймпад (30хв',
    category: 'Розважальні послуги',
    costPerUnit: 0.00,
    sellingPrice: 50.00,
    markup: 0,
    status: 'active',
  },
  {
    id: '3',
    code: 'VXX',
    name: 'VR 30 хв',
    category: 'Розважальні послуги',
    costPerUnit: 1.00,
    sellingPrice: 100.00,
    markup: 9900,
    status: 'active',
  },
  {
    id: '4',
    code: 'VD1',
    name: 'VR вихід (1 год)',
    category: 'Розважальні послуги',
    costPerUnit: 100.00,
    sellingPrice: 1000.00,
    markup: 900,
    status: 'active',
  },
  {
    id: '5',
    code: 'А1П',
    name: 'Аквариум 1 дитина',
    category: 'Розважальні послуги',
    costPerUnit: 1.00,
    sellingPrice: 80.00,
    markup: 7900,
    status: 'active',
  },
];

export const MOCK_INVOICE_ROWS: InvoiceRow[] = [
  {
    id: '1',
    name: 'Грошева орієнтація для Дітячого розважального центру Ж',
    type: 'Готівка',
    balance: 2708.04,
    status: 'active',
  },
  {
    id: '2',
    name: 'карта Натаца',
    type: 'Банківська карта',
    balance: 0.00,
    status: 'active',
  },
  {
    id: '3',
    name: 'оцід рахунок',
    type: 'Безготівковий рахунок',
    balance: 222.07,
    status: 'active',
  },
  {
    id: '4',
    name: 'Розрахунковий рахунок Приват',
    type: 'Безготівковий рахунок',
    balance: 10608.04,
    status: 'active',
  },
  {
    id: '5',
    name: 'Сайф',
    type: 'Готівка',
    balance: -9951.70,
    status: 'active',
  },
  {
    id: '6',
    name: 'Разом',
    type: 'Разом',
    balance: 3586.45,
    status: 'inactive',
  },
];
